package com.sample.app

import com.sample.app.model.Student;
import com.sample.app.model.Student.GRADE;

rule "Classify student grade to second class"
	when
		$stud: Student(passed == true && percentage < 60)
	then
		$stud.setGrade(GRADE.SECOND_CLASS);
end

rule "Classify student grade to first class"
	when
		$stud: Student(passed == true && (percentage > 60 && percentage < 70))
	then
		$stud.setGrade(GRADE.FIRST_CLASS);
end

rule "Classify student grade to distinction"
	when
		$stud: Student(passed == true && percentage > 70)
	then
		$stud.setGrade(GRADE.DISTINCTION);
end